Anssi bp 028 R14
seapath/ansible pull request #140
Opened 2023-02-14 12:33 UTC by lucbeaufils

The new version adds test for ANSSI-BP-028-R14.

SFL: #8654
Signed-off-by: Luc BEAUFILS <luc.beaufils@savoirfairelinux.com>

2023-02-14 15:01 UTC, deribaucourt requested changes

2023-02-14 15:01 UTC, deribaucourt commented on src/debian/90-sysctl-hardening.conf
> +fs.protected_fifos = 2
Misleading since this you found that these settings are overriden. It would be best to just remove them here.

2023-02-15 10:56 UTC, deribaucourt approved these changes

2023-02-15 11:17 UTC, dupremathieu requested changes
Please remove SFL: #8654

2023-02-15 14:03 UTC, dupremathieu approved these changes

2023-02-16 09:18 UTC, closed without merging