gen_cyclic_test: add latency limit
seapath/ansible pull request #552
Opened 2024-07-08 12:01 UTC by bchedotel

2024-07-10 07:45 UTC, dupremathieu requested changes
Add a commit description.

2024-07-10 07:47 UTC, dupremathieu reviewed
If the limit in launch-yocto is always 100, why make the limit changeable here?

2024-07-10 07:50 UTC, eroussy requested changes

2024-07-10 07:50 UTC, eroussy commented on scripts/gen_cyclic_test.sh
> -            -|--)
Why this modification ?

2024-07-10 07:50 UTC, eroussy commented on scripts/gen_cyclic_test.sh
> +    # Append the limit line if LIMIT is set
Wrong comment

2024-07-10 07:50 UTC, eroussy commented on scripts/gen_cyclic_test.sh
> +# Define template
It is better to put all the adoc template part in the CI repository.

May be you could move this entire script in the CI repository ?

2024-07-10 14:26 UTC, eroussy approved these changes

2024-07-11 12:33 UTC, dupremathieu approved these changes

2024-07-11 12:33 UTC, merged