add qDevice and qNetd configuration
seapath/ansible pull request #596
Opened 2024-08-27 12:45 UTC by dupremathieu

This PR adds the configuration of qDevice and qNetd daemons to the cluster_setup_ha playbook. The qDevice and qNetd daemons are used to provide a quorum without the need of a third corosync node. This is useful when the cluster has only two or an even number of nodes.

2024-08-28 11:31 UTC, Revalioli commented on playbooks/cluster_setup_ha.yaml
> +# Configure qDevice and qNetd
Could this be put in a sub-playbook or in roles ? This is a lot of tasks, and the file would be >300 lines long

2024-08-28 12:05 UTC, Revalioli commented on playbooks/cluster_setup_ha.yaml
> +# Configure qDevice and qNetd
Also it would allow having one check on the `corosync_use_qdevice` variable

2024-08-28 12:09 UTC, Revalioli commented on ansible-requirements.yaml
> +      version: "5a99ca31b82b5d416ce3ee21f251411b4f461d5c"
In the final PR, merge first the PR in corosync-ansible and then simply state that you update the ref in the commit message

2024-08-28 12:11 UTC, Revalioli requested changes
See comments

2024-09-13 08:07 UTC, dupremathieu commented
qDevice / qNetd are too complex.

2024-09-13 08:07 UTC, closed without merging