roles: add variables documentation
seapath/ansible pull request #671
Opened 2024-12-18 15:57 UTC by dupremathieu

Update the role's documentations to include the variables that can be set for each role.

Also move the default variables values which were in the playbooks to the roles themselves.

2024-12-19 17:47 UTC, insatomcat approved these changes

2025-01-06 09:50 UTC, eroussy requested changes

2025-01-06 09:50 UTC, eroussy commented on roles/centos/README.md
> +|----------------------|-------------|--------------------------------------------------------------------|
You should put a "required" column in this table, as well as a "Default" column if relevant.

2025-01-06 09:50 UTC, eroussy commented on roles/centos_hypervisor/README.md
> +| isolcpus                  | String       | CPU cores  isolate. Comma separated values, range can be defined using a dash: e.g. 4,6-7,10                                             |
You should put a "required" column in this table, as well as a "Default" column if relevant.

2025-01-06 09:50 UTC, eroussy commented on roles/centos_physical_machine/README.md
> +|--------------------------------|-------------|--------------------------------------------------------------------------------------------------------------------------------------|
You should put a "required" column in this table, as well as a "Default" column if relevant.

2025-01-06 09:50 UTC, eroussy commented on roles/configure_ha/README.md
> +| tmpdir                  | no       | String      | /tmp    | Tempory directory path to use                                                  |
Tempo**ra**ry

2025-01-06 09:50 UTC, eroussy commented on roles/configure_ha/README.md
> +| corosync_node_list      | yes      | String list |         | List of all corosync nodes. Usualy `{{ groups['cluster_machines'] \| list }}`  |
Usua**l**ly

2025-01-06 09:50 UTC, eroussy commented on roles/configure_ha/README.md
> +| admin_cluster_ip        | no       | String      |         | IP of the REST API. If not set the m-manager REST API will be disabled even if `enable_vmmgr_http_api is set to true` |
**v**m-manager

2025-01-06 09:50 UTC, eroussy commented on roles/debian/README.md
> +|----------------------|-------------|--------------------------------------------------------------------|
You should put a "required" column in this table, as well as a "Default" column if relevant.

2025-01-06 09:50 UTC, eroussy commented on roles/debian_hardening/README.md
> +| Variable        | Type   | Comments                        |
You should put a "required" column in this table, as well as a "Default" column if relevant.

2025-01-06 09:50 UTC, eroussy commented on roles/debian_hypervisor/README.md
> +| isolcpus                  | String       | CPU cores  isolate. Comma separated values, range can be defined using a dash: e.g. 4,6-7,10                                             |
You should put a "required" column in this table, as well as a "Default" column if relevant.

2025-01-06 09:50 UTC, eroussy commented on roles/deploy_vms_cluster/README.md
> +
Add SEAPATH wiki link : https://lf-energy.atlassian.net/wiki/spaces/SEAP/pages/31821162/SEAPATH+libvirt+documentation

2025-01-06 09:50 UTC, eroussy commented on roles/yocto/README.md
> +    - { role: seapath_ansible.kernel_params }
The role will not be accessible this way.
The correct path is `seapath_ansible.yocto.kernel_params`

2025-01-06 09:50 UTC, eroussy commented on roles/yocto/README.md
> +    - { role: seapath_ansible.hugepages }
The role will not be accessible this way.
The correct path is seapath_ansible.yocto.hugepages

2025-01-07 08:07 UTC, eroussy submitted a review, later dismissed

2025-01-07 08:45 UTC, eroussy approved these changes

2025-01-07 09:18 UTC, merged